// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigurationSpecApplyConfiguration represents an declarative configuration of the ConfigurationSpec type for use
// with apply.
type ConfigurationSpecApplyConfiguration struct {
	TracingSpec *TracingSpecApplyConfiguration `json:"tracing,omitempty"`
}

// ConfigurationSpecApplyConfiguration constructs an declarative configuration of the ConfigurationSpec type for use with
// apply.
func ConfigurationSpec() *ConfigurationSpecApplyConfiguration {
	return &ConfigurationSpecApplyConfiguration{}
}

// WithTracingSpec sets the TracingSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TracingSpec field is set to the value of the last call.
func (b *ConfigurationSpecApplyConfiguration) WithTracingSpec(value *TracingSpecApplyConfiguration) *ConfigurationSpecApplyConfiguration {
	b.TracingSpec = value
	return b
}
