// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	eventingv1alpha1 "github.com/w-h-a/crd/pkg/apis/eventing/v1alpha1"
	versioned "github.com/w-h-a/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/w-h-a/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/w-h-a/crd/pkg/client/listers/eventing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EventSourceInformer provides access to a shared informer and lister for
// EventSources.
type EventSourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EventSourceLister
}

type eventSourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEventSourceInformer constructs a new informer for EventSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEventSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEventSourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEventSourceInformer constructs a new informer for EventSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEventSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventingV1alpha1().EventSources(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventingV1alpha1().EventSources(namespace).Watch(context.TODO(), options)
			},
		},
		&eventingv1alpha1.EventSource{},
		resyncPeriod,
		indexers,
	)
}

func (f *eventSourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEventSourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eventSourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&eventingv1alpha1.EventSource{}, f.defaultInformer)
}

func (f *eventSourceInformer) Lister() v1alpha1.EventSourceLister {
	return v1alpha1.NewEventSourceLister(f.Informer().GetIndexer())
}
