// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/w-h-a/crd/pkg/client/clientset/versioned/typed/configuration/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeConfigurationV1alpha1 struct {
	*testing.Fake
}

func (c *FakeConfigurationV1alpha1) Configurations(namespace string) v1alpha1.ConfigurationInterface {
	return &FakeConfigurations{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeConfigurationV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
