// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EventSourceListerExpansion allows custom methods to be added to
// EventSourceLister.
type EventSourceListerExpansion interface{}

// EventSourceNamespaceListerExpansion allows custom methods to be added to
// EventSourceNamespaceLister.
type EventSourceNamespaceListerExpansion interface{}
